/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProxyMirrorIndexImport } from './routes/proxy/$mirror/index'
import { Route as ProxyMirrorViewIdImport } from './routes/proxy/$mirror/view.$id'
import { Route as ProxyMirrorUserIdImport } from './routes/proxy/$mirror/user.$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProxyMirrorIndexRoute = ProxyMirrorIndexImport.update({
  id: '/proxy/$mirror/',
  path: '/proxy/$mirror/',
  getParentRoute: () => rootRoute,
} as any)

const ProxyMirrorViewIdRoute = ProxyMirrorViewIdImport.update({
  id: '/proxy/$mirror/view/$id',
  path: '/proxy/$mirror/view/$id',
  getParentRoute: () => rootRoute,
} as any)

const ProxyMirrorUserIdRoute = ProxyMirrorUserIdImport.update({
  id: '/proxy/$mirror/user/$id',
  path: '/proxy/$mirror/user/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/proxy/$mirror/': {
      id: '/proxy/$mirror/'
      path: '/proxy/$mirror'
      fullPath: '/proxy/$mirror'
      preLoaderRoute: typeof ProxyMirrorIndexImport
      parentRoute: typeof rootRoute
    }
    '/proxy/$mirror/user/$id': {
      id: '/proxy/$mirror/user/$id'
      path: '/proxy/$mirror/user/$id'
      fullPath: '/proxy/$mirror/user/$id'
      preLoaderRoute: typeof ProxyMirrorUserIdImport
      parentRoute: typeof rootRoute
    }
    '/proxy/$mirror/view/$id': {
      id: '/proxy/$mirror/view/$id'
      path: '/proxy/$mirror/view/$id'
      fullPath: '/proxy/$mirror/view/$id'
      preLoaderRoute: typeof ProxyMirrorViewIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proxy/$mirror': typeof ProxyMirrorIndexRoute
  '/proxy/$mirror/user/$id': typeof ProxyMirrorUserIdRoute
  '/proxy/$mirror/view/$id': typeof ProxyMirrorViewIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proxy/$mirror': typeof ProxyMirrorIndexRoute
  '/proxy/$mirror/user/$id': typeof ProxyMirrorUserIdRoute
  '/proxy/$mirror/view/$id': typeof ProxyMirrorViewIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/proxy/$mirror/': typeof ProxyMirrorIndexRoute
  '/proxy/$mirror/user/$id': typeof ProxyMirrorUserIdRoute
  '/proxy/$mirror/view/$id': typeof ProxyMirrorViewIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/proxy/$mirror'
    | '/proxy/$mirror/user/$id'
    | '/proxy/$mirror/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/proxy/$mirror'
    | '/proxy/$mirror/user/$id'
    | '/proxy/$mirror/view/$id'
  id:
    | '__root__'
    | '/'
    | '/proxy/$mirror/'
    | '/proxy/$mirror/user/$id'
    | '/proxy/$mirror/view/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProxyMirrorIndexRoute: typeof ProxyMirrorIndexRoute
  ProxyMirrorUserIdRoute: typeof ProxyMirrorUserIdRoute
  ProxyMirrorViewIdRoute: typeof ProxyMirrorViewIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProxyMirrorIndexRoute: ProxyMirrorIndexRoute,
  ProxyMirrorUserIdRoute: ProxyMirrorUserIdRoute,
  ProxyMirrorViewIdRoute: ProxyMirrorViewIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/proxy/$mirror/",
        "/proxy/$mirror/user/$id",
        "/proxy/$mirror/view/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/proxy/$mirror/": {
      "filePath": "proxy/$mirror/index.tsx"
    },
    "/proxy/$mirror/user/$id": {
      "filePath": "proxy/$mirror/user.$id.tsx"
    },
    "/proxy/$mirror/view/$id": {
      "filePath": "proxy/$mirror/view.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
