/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StatsImport } from './routes/stats'
import { Route as ListImport } from './routes/_list'
import { Route as ListIndexImport } from './routes/_list.index'
import { Route as ViewIdImport } from './routes/view.$id'

// Create/Update Routes

const StatsRoute = StatsImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRoute,
} as any)

const ListRoute = ListImport.update({
  id: '/_list',
  getParentRoute: () => rootRoute,
} as any)

const ListIndexRoute = ListIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListRoute,
} as any)

const ViewIdRoute = ViewIdImport.update({
  id: '/view/$id',
  path: '/view/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_list': {
      id: '/_list'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ListImport
      parentRoute: typeof rootRoute
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsImport
      parentRoute: typeof rootRoute
    }
    '/view/$id': {
      id: '/view/$id'
      path: '/view/$id'
      fullPath: '/view/$id'
      preLoaderRoute: typeof ViewIdImport
      parentRoute: typeof rootRoute
    }
    '/_list/': {
      id: '/_list/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ListIndexImport
      parentRoute: typeof ListImport
    }
  }
}

// Create and export the route tree

interface ListRouteChildren {
  ListIndexRoute: typeof ListIndexRoute
}

const ListRouteChildren: ListRouteChildren = {
  ListIndexRoute: ListIndexRoute,
}

const ListRouteWithChildren = ListRoute._addFileChildren(ListRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof ListRouteWithChildren
  '/stats': typeof StatsRoute
  '/view/$id': typeof ViewIdRoute
  '/': typeof ListIndexRoute
}

export interface FileRoutesByTo {
  '/stats': typeof StatsRoute
  '/view/$id': typeof ViewIdRoute
  '/': typeof ListIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_list': typeof ListRouteWithChildren
  '/stats': typeof StatsRoute
  '/view/$id': typeof ViewIdRoute
  '/_list/': typeof ListIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/stats' | '/view/$id' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/stats' | '/view/$id' | '/'
  id: '__root__' | '/_list' | '/stats' | '/view/$id' | '/_list/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ListRoute: typeof ListRouteWithChildren
  StatsRoute: typeof StatsRoute
  ViewIdRoute: typeof ViewIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  ListRoute: ListRouteWithChildren,
  StatsRoute: StatsRoute,
  ViewIdRoute: ViewIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_list",
        "/stats",
        "/view/$id"
      ]
    },
    "/_list": {
      "filePath": "_list.tsx",
      "children": [
        "/_list/"
      ]
    },
    "/stats": {
      "filePath": "stats.tsx"
    },
    "/view/$id": {
      "filePath": "view.$id.tsx"
    },
    "/_list/": {
      "filePath": "_list.index.tsx",
      "parent": "/_list"
    }
  }
}
ROUTE_MANIFEST_END */
